[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "Physics and Data Science"
authors = [{name = "Alex, Fabienne, Simona, Josh, Jakub", email = "admin@durham.ac.uk"}]
dynamic = ["version", "description"]
